# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(default=None, related_name='favorite', to='quote.Quote'),
        ),
    ]
